### ISSUE TITLE
what's this line?

### ISSUE THREAD

**Issue by mircealungu** [mircealungu/se-course-best-practices#18]
in https://github.com/mircealungu/se-course-best-practices/blob/master/evaluation/Peer%20Evaluation.md there's a line which says: 

1. This shouldn't happen, as you have all contributed to the documents and all read them.

what shouldn't happen? it's not clear.

**Comment by LucvandenBrand** [comment]
It is a footnote to:
> If you really feel<sup>1</sup> you cannot grade that aspect of the work that person delivered I would like you to motivate why.

Would it be more clear if I change the number to a star?

**Comment by mircealungu** [comment]
make it a parenthetical maybe? footnotes in plaintext are not really at home :)
