### ISSUE TITLE
Future idea: recording an example presentation

### ISSUE THREAD

**Issue by LucvandenBrand** [mircealungu/se-course-best-practices#6]
As powerpoint documents can be very dependent on how they are presented, we could try to record some good presentations and publish them here (or if they have a transcript, upload that). Students would need to give permission of course.

For now, we could upload some SE1 slides we think are nice.

**Comment by mavagio** [comment]
I think Hestia had a unique presentation for SE1, as well as The Distraction Shield.

**Comment by LucvandenBrand** [comment]
Discussed over email:
It might kill the creativity of presentations to record them, and it is also slightly personal.
An alternative is to create a list of don't do's.
Maybe the slides would still be interesting enough for the example documents folder.

**Comment by mavagio** [comment]
I agree, maybe for a specific project, something will work while for others it won't.
